server:
  port: 8080

spring:
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        type:
#          org.hibernate.type: TRACE
  datasource:
    url: jdbc:postgresql://localhost:5437/test-db
    username: test-user
    password: test-password

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.engine.jdbc.bind: TRACE
    org.hibernate.engine.query.spi.SqlStatementLogger: DEBUG